version: '3.8'
services:
  RabbitMQ:
    image: rabbitmq:3-management
    container_name: RabbitMQ
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=$RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS=$RABBITMQ_DEFAULT_PASS
    ports: 
      - "15672:15672"
      - "5672:5672"
  RecordDb:
    image: postgres:14.1-alpine
    container_name: RecordDb
    restart: always
    ports:
      - "5432:5432"
    mem_limit: 300m
    environment:
      - TZ=Asia/Taipei
      - POSTGRES_USER=$DEFAULT_USER
      - POSTGRES_PASSWORD=$DEFAULT_PASSWORD
      - POSTGRES_DB=$MAIN_DB
    volumes:
      - ~/.docker-conf/RecordDb/data:/var/lib/postgresql/data
  WorkReportClient:
    container_name: WorkReportClient
    restart: always
    ports: 
      - "7001:80"
    build: 
      context: .
      dockerfile: ./WorkReportClient/Dockerfile
  WorkReportAPI:
    container_name: WorkReportAPI
    restart: always
    ports: 
      - "7002:80"
    build: 
      context: .
      dockerfile: ./WorkReportAPI/Dockerfile
  RecordWorker:
    container_name: RecordWorker
    restart: always
    ports: 
      - "7003:80"
    build: 
      context: .
      dockerfile: ./RecordWorker/Dockerfile
    depends_on:
      - RecordDb
  