// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RecordWorker.Context;

#nullable disable

namespace RecordWorker.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecordWorker.Entities.WorkReportRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_id");

                    b.Property<string>("MachineNumber")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("machine_number");

                    b.Property<int>("SpendTimeHour")
                        .HasColumnType("integer")
                        .HasColumnName("spend_time_hour");

                    b.Property<int>("SpendTimeMinute")
                        .HasColumnType("integer")
                        .HasColumnName("spend_time_minute");

                    b.Property<int>("SpendTimeSecond")
                        .HasColumnType("integer")
                        .HasColumnName("spend_time_second");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("work_report_record");
                });
#pragma warning restore 612, 618
        }
    }
}
